branch-defaults:
  initialization:
    environment: null
  master:
    environment: null
    group_suffix: null
global:
  application_name: edia-master-V2
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 18
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
